<?php

/**
 * PluginsfLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfLog');
    }
}