<?php

/**
 * PluginMailQueueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMailQueueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMailQueueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMailQueue');
    }
    
    public static function getQueuesForSend($limit = false, $execute = true)
    {
      $query = self::getInstance()->CreateQuery('q')
                ->addWhere('not sended')
                ->addWhere('not inprogress')
                ->addWhere('deleted_at is null')
                ->addWhere('validate > ? ', date('Y-m-d H:i:s'))
                ->limit($limit)
                ->orderby('id');      

      return ($execute) ? $query->execute() : $query;
    }
    
}