<?php

/**
 * PluginMailRecipientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMailRecipientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMailRecipientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMailRecipient');
    }
}