<?php

/**
 * PluginMailChannelRecipientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMailChannelRecipientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMailChannelRecipientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMailChannelRecipient');
    }
}