generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MailRecipient
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          mail_recipient
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        id:                         { label: 'Azonosító' }
        name:                       { label: 'Név' }
        zipcode:                    { label: 'Irányítószám' }
        city:                       { label: 'Település' }
        address:                    { label: 'Cim' }
        door:                       { label: 'Ajtó' }
        email:                      { label: 'E-mail' }
        phone_country:              { label: 'Telefon - ország' }
        phone_prefix:               { label: 'Telefon - szolgáltató' }
        phone:                      { label: 'Telefonszám' }
        notes:                      { label: 'Megjegyzés' }      
      list:    
        title: Feliratkozottak
        batch_actions: {}
        max_per_page:   200
        display: [id, name,  email, _address, _phone, notes]  
      filter:  ~
      form:    ~
      edit:    
        title: Szerkesztés
      new:     
        title: Új
